name: Contributor License Agreement (CLA)

on:
  pull_request_target:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  cla:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      pull-requests: write
    if: |
      (
        # The PR author is stored differently depending on the event type, see
        # https://github.com/orgs/community/discussions/25502
        (github.event_name == 'pull_request_target' && github.event.pull_request.user.login != 'argo-translation-integration[bot]')
        || (github.event_name == 'issue_comment' && github.event.issue.user.login != 'argo-translation-integration[bot]')
      )
      && (
        (github.event.issue.pull_request
          && !github.event.issue.pull_request.merged_at
          && contains(github.event.comment.body, 'signed')
        ) || (github.event.pull_request && !github.event.pull_request.merged)
      )
    steps:
      - uses: Shopify/shopify-cla-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cla-token: ${{ secrets.CLA_TOKEN }}
