name: Deploy docs site

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: dev
    - name: Generate docs
      run: |
        cd dev
        bundle exec bin/product_taxonomy docs
    - name: Upload data
      uses: actions/upload-artifact@v4
      with:
        name: data
        path: docs/_data

  build:
    runs-on: ubuntu-latest
    needs: generate_docs
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: dev
      - uses: actions/download-artifact@v4
        with:
          name: data
          path: docs/_data
      - uses: actions/configure-pages@v4
      - name: Build with Jekyll
        run: |
          cd dev
          bundle exec jekyll build --source ../docs --destination ../_site
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
